### ISSUE TITLE
AsyncPBStream is not used

### ISSUE THREAD

**Issue by jettify** [rambler-digital-solutions/aioriak#10]
Looks like dead code:
https://github.com/rambler-digital-solutions/aioriak/blob/master/aioriak%2Ftransport.py#L25-L34

anyway instead `StopIteration`, `StopAsyncIteration` should be used.

**Comment by singulared** [comment]
Yep. you are right. It's dead code from first implementation of stream operations.
Anyway now we have [RPBStreamParser](https://github.com/rambler-digital-solutions/aioriak/blob/master/aioriak%2Ftransport.py#L129-L164) with right async iterator interface implementation.
I cleaned this code in a5ae48a. Thanks.
